---
defaults:
  - _self_
  - encoder: default
  - data: default
  - trainer: vicreg
  - vicreg: default

seed: 0
device: auto
mode: online

aim:
  repo: aim://192.168.1.95:53800
  experiment: autostable-vicreg

hydra:
  job:
    chdir: true
